### PR TITLE
➕ Add prettier

### PR DESCRIPTION
**Pull request by christophvogel**
- Installed prettier with `npm i -D prettier`
- Added `prettierrc.json` with default config
- Added `.prettierignore` to ignore build artifacts
- Added `npm run prettify` to format all code
- Prettified all code

### CODE REVIEW

**Review by mrana17 — APPROVED** [review]
lgtm 🚀 gj 👍

**Review by saschahaselhuhn — APPROVED** [review]
good job

**Review by ShiningElektra — APPROVED** [review]
lgtm 👍

**Review by fre-ben — APPROVED** [review]
GJ! 🦝

**Comment by mrana17** [comment]
Thanks for the Reviews!!

**Pull request merged**
