### PR TITLE
➕  Add storybook

### PR DESCRIPTION
**Pull request by christophvogel**
- `npx sb init`
- Remove example stories folder
- Create components folder with example Button component
- Set stories folder in `.storybook/main.js`
- Load example component in `pages/index.tsx`
- Ignore `/storybook-static`
- Add `.eslintignore`

### CODE REVIEW

**Review by fgottesmann — APPROVED** [review]
lgtm! :)

**Review by fre-ben — APPROVED** [review]
LGTM 💯

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Review by sweisz — APPROVED** [review]
LGTM 👍

**Pull request merged**
